project_id = "ysbybtrbfxjfjpybmlob"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.infinitepay-checkout]
verify_jwt = false

[functions.infinitepay-webhook]
verify_jwt = false

[functions.deliver-keys]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.get-order-keys]
verify_jwt = false
